#!/bin/sh
### BEGIN INIT INFO
# Provides:          ossim-logserver
# Required-Start:    $local_fs $network $named $time $syslog mongod
# Required-Stop:     $local_fs $network $named $time $syslog mongod
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Log-archiving/parsing server for OSSIM.
### END INIT INFO

SCRIPT=/usr/bin/ossim-logserver
RUNAS=!USER!
PIDFILE=/var/run/ossim-logserver.pid

log_daemon_msg() {
    echo $1
}

log_end_msg() {
    if [ $1 -eq 0 ]; then
        echo "Complete."
    else
        echo "Failed!"
    fi
    
}

start() {
    log_daemon_msg "Starting ossim-logserver..."
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $RUNAS --chuid $RUNAS --startas $SCRIPT
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping ossim-logserver..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
     start)
        start
        ;;
     stop)
        stop
        ;;
     restart)
        stop
        start
        ;;
     *)
        echo "Usage: $0 (start|stop|restart)"
esac
